# Generated by Django 3.2.9 on 2025-04-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250425_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
    ]
