# Generated by Django 3.2.9 on 2025-04-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='was_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
